src/ta/automata.cpp, src/ta/include/ta/ata.h, src/ta/include/ta/ata_formula.h, src/ta/include/ta/automata.h, test/CMakeLists.txt, test/test_print_ata.cpp, test/test_print_ata_formula.cpp
This adds operators to print the following:
* ATA formulas
* ATA states
* ATA configurations
* ATA transitions
* ATAs
* ATA runs
=> Add operators to print ATAs and its components to an ostream

src/ta/include/ta/ata.h, src/ta/include/ta/automata.h, test/test_ata.cpp
=> ta: throw an exception if a timed word does not start with 0

src/CMakeLists.txt, src/mtl/CMakeLists.txt, src/mtl/include/mtl/MTLFormula.h, src/mtl_ata_translation/translator.cpp, src/ta/CMakeLists.txt, src/ta/include/ta/ta_regions.h, src/utilities/CMakeLists.txt, src/utilities/include/utilities/Interval.h, src/utilities/include/utilities/config.h, src/utilities/include/utilities/numbers.h, src/utilities/instantiations.cpp, test/CMakeLists.txt, test/test_interval.cpp, test/test_number_utilities.cpp, test/test_ta_region.cpp
set up utilities-library, interval has been moved so far.
=> Introduce separate utility library and first region functionality

.circleci/config.yml
Update to the latest Fedora release.
=> circleci: upgrade to Fedora 33

src/synchronous_product/CMakeLists.txt, src/synchronous_product/include/synchronous_product/search.h, src/synchronous_product/include/synchronous_product/search_tree.h, src/synchronous_product/include/synchronous_product/synchronous_product.h, src/synchronous_product/search_tree.cpp, test/CMakeLists.txt, test/test_search.cpp, test/test_synchronous_product.cpp
Fix two cases:
* If there is no bad or non-good env action, label with TOP, independent of the controller action. The controller can just decide to do nothing.
* If a good controller action and a bad environment action occur at the same time step, label with BOTTOM.
=> Incremental labeling: simultaneous good and bad action / no non-good env action

src/automata/include/automata/ta_regions.h, src/automata/ta_regions.cpp, src/synchronous_product/include/synchronous_product/create_controller.h, src/synchronous_product/include/synchronous_product/synchronous_product.h, src/visualization/include/visualization/ta_to_graphviz.h, test/CMakeLists.txt, test/railroad.cpp, test/railroad.h, test/test_create_controller.cpp, test/test_railroad.cpp, test/test_synchronous_product.cpp, test/test_ta_region.cpp, test/test_ta_visualization.cpp
Each location of the controller corresponds to a location in the search
tree. The controller selects controller actions that lead to a sub-tree
labeled with TOP. Note that the controller does not contain all possible
paths in the search tree and it may contain clock constraints that are
unnecessary. However, the resulting controller is always correct.
A simple example controller for railroad1 may look as follows:
=> Generate a controller from the labeled search tree

src/app/app.cpp, src/app/include/app/app.h, test/test_app.cpp
Add two options to the app to visualize the search tree and to save the generated controller to a proto file.
=> app: create controller proto and visualize search tree

src/app/app.cpp, src/app/include/app/app.h, src/visualization/include/visualization/ta_to_graphviz.h, test/test_app.cpp, test/test_ta_visualization.cpp
=> Optionally generate a compact controller dot graph without node labels

src/app/CMakeLists.txt, src/app/app.cpp, src/app/include/app/app.h, src/app/ta_visualizer.cpp
Simple visualization tool for a (non-product) TA.
=> app: add ta visualizer, which generates a dot from a proto TA

test/data/simple/plant.pbtxt, test/data/simple/spec.pbtxt, test/test_app.cpp, test/test_create_controller.cpp
Add a simple controller problem with a single location and two actions.
This allows us to test the controller creation end-to-end and have a simple problem for analyzing changes to the algorithm.
Also adapt the app test to use the same problem.
=> Simple controller test

src/app/app.cpp, src/search/include/search/heuristics.h, test/test_heuristics.cpp
The heuristic assigns a random cost to a node. This is especially
helpful for testing to analyze different node orders.
=> Add random heuristic

.circleci/config.yml, CMakeLists.txt, benchmark/CMakeLists.txt, src/automata/include/automata/ta.h, src/automata/include/automata/ta.hpp, src/search/include/search/search_tree.h, src/visualization/include/visualization/interactive_tree_to_graphviz.h, test/CMakeLists.txt, test/benchmark.cpp, test/benchmark_railroad.cpp, test/benchmark_robot.cpp, test/heuristics_generator.h, test/test_railroad.cpp
Benchmark the railroad and robot scenarios. The benchmark tests different heuristics and also scales the railroad problem.
=> Use googlebench to create meaningful benchmarks

.circleci/config.yml, CMakeLists.txt
Set version to 1.0.0.
Along the way, also set up circleci to run on the latest Fedora release.
=> Release 1.0

src/search/include/search/search.h, test/test_golog_search.cpp, test/test_search.cpp
This fixes a bug in the following situation: If two actions generate the
same plant successor, but with different ATA successors, then the two
successors were merged into a single successor node. However, this is
wrong, as we now can no longer distinguish which action has occurred.
Instead, we should only merge canonical words with the same reg_a if
they can be reached with the same (timed) action. If we reach a
canonical word with the same reg_a but a different action, then this
must go into a separate node.
Note that if the two successors are identical (i.e., same plant and ATA
configuration), then they will be merged regardless, as we re-use a node
if it is completely the same. This is however different to the scenario
described above, where we only compared based on reg_a. Here, we …
=> search: do not merge successors with different actions based on reg_a

test/test_search.cpp
The example is simple enough to explain and visualize the main principles of the search.
=> Add an illustrative search example as a test case

README.md
The link points to the CodeOcean Capsule created for the SCP submission.
=> Add CodeOcean link to README

.circleci/config.yml
There is a larger resource class available in the free plan, let's use it.
=> circleci: use large resource class

.circleci/config.yml, test/test_app.cpp
Adapt the 1.x release branch so it works on Fedora 36.
=> Use Fedora 36 for 1.x release

src/app/app.cpp, test/CMakeLists.txt, test/test_app.cpp
Improve the main app in several ways:
* Allow  using the composite heuristic and use it as default, as this is also done in the benchmarks
* write human-readable proto output
* make logging less verbose
* improve tests
=> Main app improvements

.circleci/config.yml, src/mtl/include/mtl/MTLFormula.h, src/mtl/include/mtl/MTLFormula.hpp, test/test_graphviz.cpp
Update the circleci config to build on Fedora 37.
Also fix some newly reported clang-tidy errors.
=> Build on Fedora 37
