.circleci/config.yml, src/libta/CMakeLists.txt, src/libta/ata.cpp, src/libta/ata_formula.cpp, src/libta/include/libta/ata.h, src/libta/include/libta/ata_formula.h, src/libta/include/libta/automata.h, test/CMakeLists.txt, test/test_ata.cpp, test/test_ata_formula.cpp
Add ATAs to libta. This adds a new class `AlternatingTimedAutomaton` closely following the definitions by [Ouaknine & Worrell, 2005](https://doi.org/10.1109/LICS.2005.33). In particular:
* Add ATA formulas, which are used to define the transitions in an ATA. ATA formulas are defined as a polymorphic type, where each formula type implements the abstract `Formula`.
* Satisfaction and minimal models for ATA formulas. Satisfaction is straightforward, following the definitions in the paper. The minimal models are actually not defined in detail in the paper, but it seemed rather straightforward to compute them. As we do not have negation in ATA formulas, we can compute the minimal models by recursively computing the minimal models of all subformulas and combining those models. As an example for …
=> Implement Alternating Timed Automata

src/ta/include/ta/ata.h, test/test_ata.cpp
In an ATA, we may reach a valid configuration with an empty set of
states, e.g., if a transition only specifies a clock constraint that is
satisfied. In that case, the minimal model of the formula is the empty
set of states.
=> ta: fix handling of empty configurations in an ATA run

.circleci/config.yml, CMakeLists.txt, README.md, cmake/CodeCoverage.cmake, test/CMakeLists.txt
Build the project with gcov compile flags if the cmake option `COVERAGE` is given (off by default).
Also adapt the CircleCI build to (separately) build with coverage and upload the results to coveralls.io.
You can also create a coverage report locally with `make coverage`.
=> Create code coverage report and upload it to coveralls

.circleci/config.yml, .codecov.yml, README.md
coveralls is weird and buggy, let's use codecov instead, which also seems easier to configure.
=> Switch to codecov for code coverage

src/mtl/include/mtl/MTLFormula.h, src/mtl_ata_translation/translator.cpp, test/CMakeLists.txt, test/test_mtlFormula.cpp, test/test_mtl_ata_translation.cpp, test/test_print_ata.cpp, test/test_print_ata_formula.cpp, test/test_print_mtl_formula.cpp
Add test cases to maximize code coverage. Those new test cases also revealed two bugs:
1. Fix an off-by-one error in MTL satisfaction check
2. Fix the MTL ATA translation for dual untils, which had conjunctions and disjunctions switched around
=> Add tests to cover untested code and fix some related bugs

src/automata/include/automata/ata.h, src/automata/include/automata/ta.h, src/synchronous_product/include/synchronous_product/operators.h, src/synchronous_product/include/synchronous_product/reg_a.h, src/synchronous_product/include/synchronous_product/search.h, src/synchronous_product/include/synchronous_product/search_tree.h, src/synchronous_product/include/synchronous_product/synchronous_product.h, test/CMakeLists.txt, test/test_search.cpp, test/test_synchronous_product.cpp, test/test_ta.cpp
Implement the main search algorithm that creates a tree over the regionalized A/B configurations. Each node consists of a set of regionalized A/B configurations, where all configurations in one node have the same `reg_A` (i.e., the A components of the word are the same). Create child nodes by creating getting all successor words of each word in the node, and then partitioning those successors by their reg_A component.
Also fix a bug where the region increment would fail to compute the correct time successor if one configuration was already maxed out, but the other one wasn't. This also simplifies the function `increment_region_indexes`.
This does not yet implement the labeling of the resulting tree, which requires further steps.
This resolves #19 and #20.
=> Implement unfolding of the search tree DT~ 

src/synchronous_product/include/synchronous_product/search.h, src/synchronous_product/include/synchronous_product/search_tree.h, src/synchronous_product/include/synchronous_product/synchronous_product.h, test/test_search.cpp, test/test_synchronous_product_print.cpp
Label the search tree recursively bottom-up, with the following rules:
* good and dead leave nodes are labeled with TOP
* bad leave nodes are labeled with BOTTOM
* a non-leave node is labeled with TOP if each child
* is labeled with TOP, or
* is only eachable with a controller action (in which case it can be ignored)
This implicitly implements the validity function mentioned in Bouyer et al, 2006, assuming that any selection is valid if it does not constrain the environment actions.
=> Implement search tree labeling

CMakeLists.txt, src/automata/include/automata/ata_formula.hpp, src/synchronous_product/include/synchronous_product/synchronous_product.h
This gives us additional warnings that are not enabled with -Wall.
=> Build with -Wextra and -Wpedantic, fix pedantic warnings

.circleci/config.yml, src/automata/automata.cpp, src/automata/include/automata/ata.h, src/automata/include/automata/ata.hpp, src/automata/include/automata/ata_formula.h, src/automata/include/automata/ata_formula.hpp, src/automata/include/automata/automata.h, src/automata/include/automata/automata.hpp, src/automata/include/automata/ta.h, src/automata/include/automata/ta.hpp, src/automata/ta.cpp, src/mtl/include/mtl/MTLFormula.h, src/mtl/include/mtl/MTLFormula.hpp, src/mtl_ata_translation/include/mtl_ata_translation/translator.h, src/synchronous_product/include/synchronous_product/search.h, src/synchronous_product/include/synchronous_product/synchronous_product.h
clang seems to be more strict regarding operator overloading in namespaces. In particular, if it finds an operator with the wrong overload in the current namespace, it no longer checks the global namespace for additional overloads. AFAIU, this is actually intended by the C++ standard, and this is a bug in GCC: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=51577 Let's not rely on the bug and instead move all operators to the global namespace.
The second problem regarding overloads is the following:
If we use a using-declaration, we cannot define the operator overload in the same namespace, as we don't actually define the type in the namespace, but merely alias it. Instead, it needs to be defined in the global namespace or the namespace of the type being aliased (e.g., `std`).
For now, just …
=> Adapt to clang and also do CI builds with clang

src/automata/include/automata/automata.h, src/automata/include/automata/ta.h, src/automata/include/automata/ta.hpp, src/automata/include/automata/ta_product.h, src/automata/include/automata/ta_product.hpp, test/CMakeLists.txt, test/test_ta_product.cpp
Add a new function `automata::ta::get_product` that construct the product of two timed automata. The resulting automaton's location set is the cartesian product of the input automata's locations.
The API already allows synchronized actions, with the following meaning: The product automaton either takes a single transition in either one of the automata for a non-synchronized action, or it simultaneously takes a transition in both automata for a synchronized action. However, we currently require the synchronized actions to be empty. Therefore, we currently always take an action in either one of the automata, not in both simultaneously.
=> Add product construction for TAs

.circleci/config.yml
Speed up the build process by splitting coverage generation and running the generation with multiple jobs. Running with `-j$(nproc)` always fails with OOM, but using `$(nproc)/4` seems to work reliably.
=> Run coverage generation in parallel and with multiple jobs

src/automata/include/automata/ta_product.h, src/automata/include/automata/ta_product.hpp, src/synchronous_product/include/synchronous_product/search.h, src/utilities/CMakeLists.txt, src/utilities/include/utilities/priority_thread_pool.h, src/utilities/include/utilities/priority_thread_pool.hpp, test/CMakeLists.txt, test/test_priority_thread_pool.cpp, test/test_railroad.cpp, test/test_search.cpp, test/test_ta_product.cpp
Add a general-purpose `ThreadPool` class to utilities, which keeps a priority queue of jobs and processes the jobs with a set of worker threads asynchronously. Jobs pushed to the pool may be any `Callable`, usually we assume it to be a `std::function`.
Also add a helper class `QueueAccess` that provides synchronous access to the pool's queue. This allows us to process the queue single-threaded and step by step, which is particularly useful for testing. Access with `QueueAccess` must not be intertwined with the pool's worker threads, i.e., it may only be used if the pool has not been started yet.
Also adapt the search to use the thread pool. Re-implement the search's `step()` function using the `QueueAccess`.
=> Add a thread pool with a priority queue for multithreading

src/synchronous_product/include/synchronous_product/heuristics.h, src/synchronous_product/include/synchronous_product/search.h, test/CMakeLists.txt, test/test_heuristics.cpp
Add an abstract class `Heuristic` and re-implement BFS as heuristic.
This does not add new heuristics yet, but serves as baseline for additional heuristics.
=> Add base support for heuristics

src/mtl/include/mtl/MTLFormula.h, src/mtl/include/mtl/MTLFormula.hpp, src/utilities/include/utilities/Interval.h, test/test_interval.cpp, test/test_mtlFormula.cpp, test/test_print_mtl_formula.cpp, test/test_search.cpp
When comparing two MTL Formulas of type until or dual until, we also need to compare the intervals. To do this, define comparison operators for Intervals and then compare the intervals when comparing MTL formulas.
For debugging purposes, also define an ostream operator for Intervals and print the interval when printing an MTL Formula.
Also adapt some tests that made wrong assumptions about intervals.
=> Also consider intervals when comparing MTL formulas

src/automata/include/automata/ta.h, src/automata/ta.proto, src/automata/ta_proto.cpp, test/test_ta.cpp, test/test_ta_proto.cpp
While ATAs allow inequality in clock constraints, TAs do not. To avoid
having two classes for clock constraints, throw an exception on
construction of a TA with an inequality constraint.
=> ta: do not allow inequality in transition guards

src/synchronous_product/include/synchronous_product/search.h, src/synchronous_product/include/synchronous_product/search_tree.h, src/synchronous_product/search_tree.cpp, test/test_railroad.cpp, test/test_search.cpp
If we have already labeled a node by means of incremental labeling, we know that the label will not change, no matter what the search on remaining children returns. Thus, we can also safely cancel the search in that sub-tree.
This require some careful multi-threading coordination. Until now, a thread always operated on a single node with a guarantee that no other thread would work on that node simultaneously. With incremental labeling, we may move up in the tree, but never down. With node canceling, we may now move up (by means of incremental labeling) and down (by means of node cancelation), causing possible conflicts. Rather than protecting the complete node with a mutex, make the node label atomic, and also add an atomic bool `is_expanded` that is true if the node has been expanded …
=> Terminate search in a sub-branch if node is labeled

src/mtl/include/mtl/MTLFormula.h, test/test_mtlFormula.cpp
The formulas finally(a, I) and globally(a, I) correspond to F_I(a) and
G_I(a) and are commonly used as logical shortcuts.
=> mtl: provide helper functions to create formulas finally and globally

src/automata/CMakeLists.txt, src/automata/include/automata/ta_product.h, src/automata/include/automata/ta_product.hpp, test/test_railroad.cpp, test/test_ta_product.cpp
We may want to compute the product of more than two automata. While
theoretically, this is possibly by computing (ta1 x (ta2 x ta3)), this
is not feasible in practice, as the result is a tuple of tuples.
Instead, take a vector of automata when computing the product and
directly compute the product of all the input automata.
This restricts the input automata to be of the same type. However, in
our applications, this restriction is acceptable.
=> Extend TA product to more than two input automata

src/utilities/graphviz/include/utilities/graphviz/graphviz.h, src/utilities/graphviz/node.cpp, src/visualization/CMakeLists.txt, src/visualization/include/visualization/ta_to_graphviz.h, src/visualization/include/visualization/tree_to_graphviz.h, src/visualization/visualization.cpp, test/CMakeLists.txt, test/test_graphviz.cpp, test/test_ta_visualization.cpp
Generate a dot graph for a TA. As an example, this is what the railroad product TA looks like:
=> Add visualization of a TA as dot graph

src/synchronous_product/include/synchronous_product/search.h, test/test_railroad.cpp
Extend the railroad example so it allows multiple crossings.
This does not contain yet any other fixes that are pending.
=> Scale railroad example to multiple crossings

src/synchronous_product/include/synchronous_product/search_tree.h
If a node has been labeled already, do not set it to canceled.
Also avoid a race condition during labeling. This may occur if a child's label is changed while we are iterating over its incoming actions, possibly resulting in a wrong label of the parent.
=> Do not cancel labeled nodes and avoid race while labeling

src/automata/include/automata/ta_regions.h, src/synchronous_product/include/synchronous_product/heuristics.h, src/synchronous_product/include/synchronous_product/search.h, test/test_heuristics.cpp, test/test_railroad.cpp
Add a heuristic that always prefers nodes with incoming actions with a low region increment, thus preferring actions that occur early. This improves performance in the railroad benchmark significantly.
For completeness' sake, also add DFS.
=> Add time heuristic

src/automata/include/automata/ta_regions.h, src/automata/ta_regions.cpp, src/synchronous_product/include/synchronous_product/create_controller.h, test/test_ta_region.cpp
If a clock reaches the max region, it should not have an upper bound, as
it may have values larger than 2*region+1.
=> controller: when we reached the max region index, do not add upper bound

src/automata/include/automata/ata_formula.h, src/automata/include/automata/ata_formula.hpp, src/mtl_ata_translation/translator.cpp, test/test_ata_formula.cpp
Directly simplify e.g. `true && false` to `false` when creating the ATA transitions. This simplifies the ATA significantly:
```
ATA:
Alphabet: {disappear, enter, finish_close, finish_open, get_near, leave, start_close, start_open}, initial location: l0, final locations: {}, transitions:
(!(finish_close) U enter) → disappear → (!(finish_close) U enter)
(!(finish_close) U enter) → enter → ⊤
(!(finish_close) U enter) → finish_close → ⊥
(!(finish_close) U enter) → finish_open → (!(finish_close) U enter)
(!(finish_close) U enter) → get_near → (!(finish_close) U enter)
(!(finish_close) U enter) → leave → (!(finish_close) U enter)
(!(finish_close) U enter) → start_close → (!(finish_close) U enter)
(!(finish_close) U enter) → start_open → (!(finish_close) U enter)
(!(finish_open) U disappear) → …
```
=> Simplify ATA formulas during construction of the spec ATA

src/mtl/include/mtl/MTLFormula.h, src/mtl/include/mtl/MTLFormula.hpp
Also use default constructors where possible, no need to define them manually.
=> Add copy assignment and move constructors for MTL formulas

src/synchronous_product/include/synchronous_product/create_controller.h, test/test_app.cpp, test/test_create_controller.cpp
Do not throw exception on top-labeled node without children during
search.
This is not actually an error, as the controller may just need to do
nothing, because any controller action leads to a bad state.
=> bugfix: allow controller to wait

src/automata/include/automata/automata.hpp, src/automata/include/automata/ta.h, src/automata/include/automata/ta_regions.h, src/automata/ta_regions.cpp, src/synchronous_product/include/synchronous_product/create_controller.h, test/test_create_controller.cpp, test/test_ta_region.cpp
We may need all transitions to the successors, e.g., if one of them is an environment action that the environment may or may not take. So just add all successors. Additionally, merge the clock constraints such that two transitions with different but adjacent region increments that lead to the same successor node are merged into one.
=> Add all good successor nodes to the controller, merge clock constraints

src/synchronous_product/include/synchronous_product/heuristics.h, test/test_heuristics.cpp
Add three heuristics:
* The `PreferEnvironmentActionHeuristic` prefers environment actions over controller actions by assigning a cost of 0 if the node has an environment action as incoming action and 1 otherwise
* The `NumCanonicalWordsHeuristic` sets as cost the number of canonical words in a node
* The `CompositeHeuristic` can be used to combine heuristics
=> Add more heuristics

src/synchronous_product/include/synchronous_product/search.h, src/synchronous_product/include/synchronous_product/search_tree.h, src/visualization/include/visualization/tree_to_graphviz.h, test/test_tree_visualization.cpp
Add a label reason to each node that shortly describes why a node has a certain label and print the label in the visualization. This greatly helps understanding what happens during search.
=> Add more detailed node description to allow analyzing the search tree

src/search/include/search/search.h, test/CMakeLists.txt, test/railroad.cpp, test/railroad.h, test/test_ata.cpp, test/test_create_controller.cpp, test/test_railroad.cpp
Generate the spec in the problem generator and run a set of benchmarks on the railroad problem.
Also fix the spec by properly using dual untils. This should actually accomplish the desired behavior (the previous spec did not).
=> Extend railroad test to a benchmark

src/visualization/include/visualization/interactive_tree_to_graphviz.h, src/visualization/include/visualization/tree_to_graphviz.h
The tool runs in a loop and asks for the next node to be added to the
visualization. It currently supports selecting a single child of the
current node and undoing a selection. Thus, the resulting graph will
always be a path (this could be extended in the future).
=> Add a tool for interactive search graph visualization

src/app/app.cpp, src/search/include/search/create_controller.h, test/test_create_controller.cpp, test/test_fischer.cpp, test/test_railroad.cpp
When creating the controller, we can safely skip all further successors
once we have found a controller action. This is because at that point,
the controller can always follow a good path, independent of the other
sub-trees.
This keeps the resulting controller much smaller, although it now
contains less options.
=> controller: skip further nodes if we have found a good controller action

src/search/include/search/heuristics.h, src/search/include/search/search.h, src/search/include/search/search_tree.h, test/test_heuristics.cpp, test/test_search.cpp
With the switch to search graphs (#97), the time heuristic was no longer working, as we could not easily traverse a path to the root.
Instead of traversing the path for every node, store the minimal number of region increments that it takes to reach a node when adding the node to the graph. This can then be directly used as value for the heuristic.
=> Fix time heuristic

src/search/include/search/synchronous_product.h, test/test_synchronous_product.cpp
This fixes a bug where a partition with only maxed out regions would be inserted in the middle instead of the end of the word, resulting in exceptions during search.
As an example, consider
```
CanonicalABWord{
{TARegionState{Location{"l0"}, "x0", 0}},
{TARegionState{Location{"l0"}, "x1", 1}},
{TARegionState{Location{"l0"}, "x3", 3}}}
```
Previously, the successor of the word was computed as
```
CanonicalABWord{
{TARegionState{Location{"l0"}, "x1", 2}},
{TARegionState{Location{"l0"}, "x3", 3}}},
{TARegionState{Location{"l0"}, "x0", 1}}
```
This PR fixes the order to:
```
CanonicalABWord{
{TARegionState{Location{"l0"}, "x1", 2}},
{TARegionState{Location{"l0"}, "x0", 1}},
{TARegionState{Location{"l0"}, "x3", 3}}}
```
=> Fix canonical word order if one partition is maxed out

src/search/include/search/search_tree.h, src/search/include/search/synchronous_product.h, test/test_synchronous_product.cpp
Make sure that all regionalized configurations with a maxed region index are in the last partition of the canonical word.
This effectively ignores the fractional part of all clocks that are in the max region and avoids issues if we can reach the same configuration but with different partitioning of the maxed clocks.
=> Always merge all maxed regions in a canonical word into one partition

.circleci/config.yml, CMakeLists.txt, src/app/app.cpp, src/search/include/search/search.h, test/CMakeLists.txt, test/benchmark_conveyor_belt.cpp, test/benchmark_railroad.cpp, test/benchmark_robot.cpp
This adds the conveyor belt benchmark and adapts or extends and unifies the other benchmarks.
Commit c3f38841f24c48f091b9fddfa45eeda6c2c91394 also contains a fix for a bug if we have a loop in the search graph, which sometimes results in no labeling, as we did not properly detect monotonic domination.
This is the set of benchmarks as used for SEFM.
=> Extend benchmarks

.circleci/config.yml
Auto-deploy doxygen docs to github pages by:
1. Persisting the created docs during the build process to the workspace
2. Deploying them using [npm `gh-pages`](https://www.npmjs.com/package/gh-pages)
The docs are deployed to the `docs` subfolder in the branch so we can keep the circleci config file that sets up circleci to ignore the branch (see 8f1414ac77d403124e36a6473e6f3a0d414558bc).
=> Auto-deploy doxygen docs

src/app/CMakeLists.txt, src/automata/CMakeLists.txt, src/mtl_ata_translation/CMakeLists.txt, src/search/CMakeLists.txt, src/utilities/CMakeLists.txt, test/CMakeLists.txt
The library was already named libautomata, adapt the target accordingly.
=> automata: rename target from ta to automata

src/app/app.cpp, src/app/include/app/app.h, src/search/include/search/search_tree.h, src/visualization/include/visualization/interactive_tree_to_graphviz.h, src/visualization/visualization.cpp, test/test_tree_visualization.cpp
Improve interactive debugging with several features:
* Use vim-like modes, which allows navigating in the tree, e.g., to move to the parent to select another child. There are three modes:
* INSERT: to select a new child to display
* NAVIGATE: to move around the tree without selecting additional children
* INSERT AND FOLLOW: insert a node and simultaneously select the new node
* Allow selecting all children at once
* Add an option to the main app to launch interactive visualization
* Improve logging and help messages in the interactive debugger
=> Enhance interactive debugging

examples/railroad/spec.pbtxt, src/mtl/include/mtl/MTLFormula.hpp, test/test_mtlFormula.cpp, test/test_mtl_proto.cpp, test/test_print_mtl_formula.cpp
I initially thought that this is a bug in the protobuf import, but it turns out we just did not print conjunctions and disjunctions with less or more than two operands correctly. Thus,
* fix the output of conjunctions and disjunctions
* extend the print test cases to make sure it is working correctly
* also extend the satisfaction checks to cover all cases, just to make sure the formula works as expected
* extend the protobuf import test to also have three conjuncts and disjuncts
=> Fix ostream output for conjunctions/disjunctions with less or more than two operands

test/test_graphviz.cpp, test/test_ta_visualization.cpp, test/test_tree_visualization.cpp, test/test_xml_writer.cpp
The Contains matcher for strings was renamed to ContainsSubstring, assumingly to distinguish it from the containers' Contains. Adapt accordingly.
Also use the same matcher in the XML writer test.
=> Adapt to Catch2 renaming: Contains -> ContainsSubstring

test/railroad_location.cpp, test/test_create_controller.cpp, test/test_fischer.cpp, test/test_golog_search.cpp, test/test_golog_words.cpp, test/test_mtl_ata_translation.cpp, test/test_railroad.cpp, test/test_railroad_location.cpp, test/test_ta_visualization.cpp, test/test_tree_visualization.cpp
There is no need to prefix every member with the namespace prefix if we
have already imported the complete namespace with a using-directive.
This is a follow-up to #124.
=> Remove unnecessary ns prefix `tacos::` if we have imported the ns

src/automata/include/automata/automata.h, src/automata/include/automata/ta.h, src/automata/include/automata/ta.hpp, src/mtl/include/mtl/MTLFormula.h, src/mtl/include/mtl/MTLFormula.hpp, src/mtl/mtl.proto, src/mtl_ata_translation/include/mtl_ata_translation/translator.hpp, src/utilities/include/utilities/types.h, test/test_mtlFormula.cpp
Consistently use `Endpoint` where we are referring to an Endpoint (rather than Time).
Also remove duplicate definitions of Endpoint and move the definition to the `utilities/types.h` header.
This was noticed during the review for #124.
=> mtl: an interval endpoint must be uint, not double

src/automata/include/automata/ata.h, src/automata/include/automata/ata.hpp, test/test_ata.cpp, test/test_mtl_ata_translation.cpp
To improve testing and allow ATAWords not defined over strings, introduce additional typedefs.
=> Introduce better typedefs for ATAs

src/mtl/include/mtl/MTLFormula.hpp, src/mtl_ata_translation/include/mtl_ata_translation/translator.h, src/mtl_ata_translation/include/mtl_ata_translation/translator.hpp, src/utilities/include/utilities/powerset.h, test/CMakeLists.txt, test/test_mtl_ata_translation.cpp, test/test_powerset.cpp
Instead of defining a timed word as a sequence over single symbols (and timesteps), we may also want to have a set of symbols at each step. This is particularly useful when using location constraints, as locations are typically labeled with sets of properties that we may compare against.
To create the ATA, we simply construct the powerset of all symbols that occur in the input MTL formula.
=> Allow MTL -> ATA translation for MTL constraints with set semantics

third_party/third_party.cmake
Pin the version so upstream updates do not break our build.
This was not possibly previously, as the available pre-release was too old.
=> Pin the version of catch2

src/search/include/search/search.h, test/test_search.cpp
This fixes a bug in the following situation: If two actions generate the
same plant successor, but with different ATA successors, then the two
successors were merged into a single successor node. However, this is
wrong, as we now can no longer distinguish which action has occurred.
Instead, we should only merge canonical words with the same reg_a if
they can be reached with the same (timed) action. If we reach a
canonical word with the same reg_a but a different action, then this
must go into a separate node.
Note that if the two successors are identical (i.e., same plant and ATA
configuration), then they will be merged regardless, as we re-use a node
if it is completely the same. This is however different to the scenario
described above, where we only compared based on reg_a. Here, we …
=> search: do not merge successors with different actions based on reg_a 

src/search/include/search/operators.h, src/search/include/search/search.h, src/search/include/search/search_tree.h, src/search/search_tree.cpp, src/visualization/include/visualization/tree_to_graphviz.h, test/test_search.cpp, test/test_synchronous_product.cpp
While techically, a node always monotonically dominates itself, we must exclude self loops from the check, as treating self loops as monotonically dominating is dangerous: The initial assumption of monotonic domination is that if we could reach a
bad configuration from the current node, then we can also reach that configuration from the dominated ancestor, thus we can stop expanding the current node. However, if the ancestor is actually the same node, then we must not stop expansion, as this means  that we check neither node. Therefore, we must exclude self loops in the monotonic domination check.
Consider the following example (from [this test case](https://github.com/morxa/tacos/blob/cb90f481925e0c72c1e6a2d39d0a0a54ef1d9d21/test/test_search.cpp#L251)):
The node in the middle is …
=> Exclude self loops in monotonic domination checks

src/utilities/include/utilities/Interval.h, test/test_interval.cpp, test/test_print_mtl_formula.cpp
We should use "()" for strict and "[]" for weak interval bounds, not the
other way around.
=> utilities: correctly print strict and weak interval bounds

src/search/include/search/search.h, test/test_search.cpp
If we have some loop of unlabeled nodes, then the label function would
recurse into the children infinitely often. To avoid this, track which
nodes we have already seen and abort the labeling if we have already
visited the current node. This means that if we encounter a loop, then
the whole loop may not obtain a label, as it is possible to just stay in
the loop indefinitely. As no node is labeled with BAD, any node that is
a parent of one of the loop's nodes may be labeled with GOOD (unless
there is some other reason why it is bad). Note that this may also mean
that the controller can just stay in the loop to obtain a winning
strategy.
Note that the first commit simply moves the label function into a free function. The actual fix is in the second commit …
=> Avoid infinite recursion in label function

.circleci/config.yml, CMakeLists.txt, test/CMakeLists.txt, test/benchmark_robot.cpp
This disables the largest benchmarks by default and therefore reduces
the total running time significantly.
This is a backport of #145.
=> benchmarks: add cmake flag for large benchmarks, disable by default

.circleci/config.yml, CMakeLists.txt, src/automata/CMakeLists.txt, src/automata/include/automata/ta.hpp, src/mtl/CMakeLists.txt, src/search/include/search/synchronous_product.h, test/CMakeLists.txt, test/benchmark_conveyor_belt.cpp, test/benchmark_railroad.cpp, test/benchmark_robot.cpp, test/csma_cd.cpp, test/csma_cd.h, test/fischer.cpp, test/fischer.h, test/railroad.cpp, test/railroad.h, test/railroad_location.cpp, test/railroad_location.h, test/test_ata.cpp, test/test_csma_cd.cpp, test/test_heuristics.cpp, test/test_print_ata.cpp, test/test_railroad.cpp, test/test_railroad_location.cpp, third_party/third_party.cmake
Add a build option to run the build with clang-tidy enabled. For now, only enable some `bugprone` warnings and fix all warnings produced by clang-tidy.
=> Optionally run clang-tidy and fix some clang-tidy warnings

test/benchmark_railroad.cpp, test/benchmark_robot.cpp
The robot benchmark is not large. Instead, railroad scaled should have
been marked as large.
This is a backport of #149.
=> benchmarks: mark scaled railroad (instead of robot) as large benchmark

src/automata/include/automata/ata_formula.h, src/automata/include/automata/ata_formula.hpp, src/mtl_ata_translation/include/mtl_ata_translation/translator.hpp, test/CMakeLists.txt, test/test_mtl_ata_translation.cpp
We made the incorrect assumption that an MTL conjunction (disjunction) always has exactly two conjuncts (disjuncts). However, it may contain any number of subformulas (the subformulas are stored in a vector), which resulted in incorrect translations. In particular, we would only consider the first and last conjunct (disjunct) and ignore the rest.
Fix this by translating the MTLFormula by recursively creating conjunctions (disjunctions) until we have reached a single subformula. This means that the ATA conjunction (disjunction) still only consists of exactly two subformulas, but these are then again conjunctions (disjunctions) if we are translating a formula with more than two subformulas.
We may in the future decide to also have an arbitrary number of subformulas in ATA conjunctions …
=> Fix MTL->ATA Translation for conjunctions and disjunctions with >2 subformulas

test/benchmark_conveyor_belt.cpp, test/benchmark_railroad.cpp, test/benchmark_robot.cpp
Our benchmarks are large enough that measurements in nanoseconds do not
convey additional information and are much harder to read. Switch to
seconds for all benchmarks.
This is a backport of #155.
=> benchmarks: measure time in seconds, not nanoseconds

src/gocos/golog_adapter.cpp, src/gocos/golog_program.cpp, src/gocos/include/gocos/golog_adapter.h, src/gocos/include/gocos/golog_adapter.hpp, src/search/include/search/adapter.h, test/test_golog_search.cpp, test/test_golog_words.cpp
Whenever a start action occurs, insert a clock and reset it to 0.
Whenever an end action occurs, compare the clock value against the
action duration. More precisely, pass the current clock value to gologpp
so it only generates a successor if the duration constraint is
satisfied.
This allows to model some kind of timing constraint in golog without
introducing full clock constraints.
=> Provide a clock for each Golog action and check action durations

src/search/include/search/canonical_word.h, src/search/include/search/search.h, src/search/include/search/synchronous_product.h, test/test_synchronous_product.cpp
Add the following checks:
* A canonical word should not contain a region index that is strictly larger than the max region index. If that happens, then the input was invalid, e.g., the given max constant is not actually the max constant.
* Make sure that every action is either a ctl or an env action (i.e., it must occur in one of the two sets).
=> Add assertions to avoid two common pitfalls

src/search/include/search/search.h, src/search/include/search/synchronous_product.h, test/test_create_controller.cpp, test/test_search.cpp, test/test_synchronous_product.cpp
If a node contains a word that already only contains clocks in the maximal region, then it only has a single time successors, because there is no increment that changes the successor. However, the node may have another word with more time successors.  When computing the successor nodes, we also need to consider the first word, even for a higher time increment. Otherwise, the successor of the first word is missing from the successor node.
The second part fixes a related but more general problem:
When computing the time successor for a node, we need to
consider all canonical words in the node. Parts of this was fixed in the first part (28e054f8b3ff4811e53ed876fbaae64b7b6e17be), however, that fix is incomplete. As an example, consider a
node with two words:
1. `{ (l0, c, 1) }`
2. `{ (ATA, 0) …
=> Compute time successors for all possible increments of the node

src/automata/include/automata/ata.hpp
This fixes a compiler error with GCC with enabled optimization.
=> Explicitly construct variant to avoid compiler error

.circleci/config.yml
Explicitly build with build type 'Debug' in the default step. This is necessary because some libraries default to 'Release', which may cause problems. In particular, golog++ causes segfaults if build with clang and no specified build type.
In addition to the Debug build type, also build with type 'Release' to make sure that we can also build that configuration without errors.
This is a backport of #170 .
=> circleci: build both Debug and Release build types

examples/railroad/spec.pbtxt
This requires that the gate is closed for at least 1s before the train may enter.
=> railroad example: add timing constraint on enter/finish_close

src/gocos/golog_adapter.cpp, src/gocos/golog_program.cpp, src/gocos/golog_symbols.cpp, src/gocos/include/gocos/golog_adapter.hpp, src/gocos/include/gocos/golog_program.h, src/search/include/search/search.h, test/test_golog_search.cpp, test/test_golog_words.cpp
Instead of comparing the locations based on the history, use the satisfied fluents. This is necessary because the history always grows, even if we are in a world state that is the same as a previous state.
This also  requires us to distinguish between the fluents that are relevant to check the MTL specification and all fluents that are satisfied. We need to compare based on the latter, because we may be in two different states even if all the fluents relevant for the specification are the same.
Along the way, also add two minor improvements:
* Add a special predicate `occ(action)` that can be used in the specification to check whether a certain action has occurred
* In a state-based setting, directly initialize the ATA configuration with the fluents that are satisfied in the initial …
=> Compare Golog locations based on fluents

.circleci/config.yml
The circleci keys may have been compromised, therefore rotate them: https://circleci.com/blog/january-4-2023-security-alert/
=> circleci: update ssh deploy key for GitHub Pages

third_party/third_party.cmake
Also do not overwrite the output width. This is now a cmake cache variable, so each dev should set it on their own, e.g., with
```
cmake -B build -DCATCH_CONFIG_CONSOLE_WIDTH=200
```
=> third_party: upgrade to Catch2 v3.3.0
